/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frinthesia.gui.panel;

/**
 * MIDI browser panel.
 *
 * @version 0.1.0 2015/11/28
 * @author Frinthesia Project
 */
public class PlayMidiPanel extends javax.swing.JPanel implements FrinthesiaPanel {

    /**
     * Creates new form midiBrowserPanel
     */
    public PlayMidiPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        backOnlyButton = new javax.swing.JButton();
        playPauseButton = new javax.swing.JButton();
        positionPanel = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.BorderLayout());

        backOnlyButton.setText("<< BACK");
        backOnlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backOnlyButtonActionPerformed(evt);
            }
        });

        playPauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frinthesia/resources/icons/pause16.png"))); // NOI18N

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backOnlyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(playPauseButton)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playPauseButton)
                    .addComponent(backOnlyButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(controlPanel, java.awt.BorderLayout.PAGE_START);

        progressBar.setValue(30);

        javax.swing.GroupLayout positionPanelLayout = new javax.swing.GroupLayout(positionPanel);
        positionPanel.setLayout(positionPanelLayout);
        positionPanelLayout.setHorizontalGroup(
            positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        positionPanelLayout.setVerticalGroup(
            positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(positionPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void backOnlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backOnlyButtonActionPerformed

    }//GEN-LAST:event_backOnlyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backOnlyButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton playPauseButton;
    private javax.swing.JPanel positionPanel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean canNext() {
        return false;
    }

    @Override
    public FrinthesiaPanelRecord getPreviousPanel() {
        return null;
    }

    @Override
    public FrinthesiaPanelRecord getNextPanel() {
        return null;
    }
}
